// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zeyhackzkeryuevoykci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpleWhhY2t6a2VyeXVldm95a2NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MjY1NzIsImV4cCI6MjA2NjUwMjU3Mn0.CgQAiU2fTExbLQCofr4pnTxAgqkdya147QYSiScs14k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);